'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClockWorkOrder

    '''<summary>
    '''btnClockOnWO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClockOnWO As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClockOffWO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClockOffWO As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPause As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddPauseReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddPauseReason As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''odsPauseReasons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPauseReasons As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''gvOrdersToClock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOrdersToClock As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsWorkOrdersToClock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsWorkOrdersToClock As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
