<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="TimeClockUpdate.aspx.vb" Inherits="SOSiQ.TimeClockUpdate" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <br />
    <div class="jumbotron"><h3>Update Clock in/out</h3>
        
        <h5>Use this page to update the time a team member clocked in or out</h5>

    </div>

    <div>
        <table>
            <tr>
                <td style="height: 45px">Team Member:</td>
                <td style="height: 45px">
                    <asp:DropDownList ID="ddlTeamMembers" runat="server" DataSourceID="odsEmployees" DataTextField="LastName" DataValueField="EmployeeID"></asp:DropDownList>
                    <asp:ObjectDataSource ID="odsEmployees" runat="server" OldValuesParameterFormatString="original_{0}" SelectMethod="GetEmployees" TypeName="SOSiQ.SOSiQsqlDBTableAdapters.ShowMeActiveEmployeesBySiteTableAdapter">
                        <SelectParameters>
                                 <asp:ControlParameter ControlID="lblsiteid" Name="SiteID" />
                            <asp:Parameter DefaultValue="False" Name="bAllEmployees" Type="Boolean" />
                        </SelectParameters>
                    </asp:ObjectDataSource>
                </td>
                <td rowspan="2"><asp:Button ID="btnView" runat="server" Text="View Date" CssClass="btn-lg" /></td>

            </tr>
            <tr>
                <td>Date to edit:</td>
                <td>
                    <asp:TextBox ID="txtDate" runat="server" TextMode="Date"></asp:TextBox></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>&nbsp;</td>
            </tr>
        </table>

    </div>

    <br />
    <hr />

    <div>
        <asp:GridView ID="gvTimeStamps" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" CssClass="table-condensed" GridLines="Vertical" AutoGenerateEditButton="True" ShowFooter="True" HeaderStyle-CssClass="FixedHeader" AutoGenerateDeleteButton="True">
            <AlternatingRowStyle BackColor="Gainsboro" />
            <Columns>
                <asp:TemplateField HeaderText="Punch ID" SortExpression="PunchID">
                    <ItemTemplate>
                        <asp:Label ID="lblPunchID" runat="server" Text='<%# Bind("PunchID") %>'></asp:Label></ItemTemplate>
                </asp:TemplateField>
                
                <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" SortExpression="EmployeeID" readonly="true"/>
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" readonly="true"/>
                <asp:TemplateField HeaderText="FirstName" SortExpression="FirstName">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("FirstName") %>'></asp:Label>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:Button ID="btnInsertEmployeePunch" runat="server" Text="Add" OnClick="Button1_Click" />
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("FirstName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Punch Date Time">
                    <FooterTemplate>
                        <asp:TextBox ID="txtInsertPunchDateTime" runat="server" TextMode="DateTimeLocal"></asp:TextBox>
                    </FooterTemplate>
                    <ItemTemplate>
                                <asp:Label ID="lblPunchDateTime" runat="server" Text='<%# Eval("punchdatetime") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtPunchDateTime" runat="server" TextMode="DateTimeLocal" Text='<%#Eval("punchdatetime", "{0:yyyy-MM-ddTHH:mm}") %>'></asp:TextBox>

                    </EditItemTemplate>

                </asp:TemplateField>
                <asp:TemplateField HeaderText="PunchTypeDesc" SortExpression="PunchTypeDesc">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddPunchTypeEditItem" runat="server" DataSourceID="odsPunchTypes" DataTextField="PunchTypeDesc" DataValueField="PunchTypeDesc" AppendDataBoundItems="true"   selectedvalue='<%#Bind("PunchTypeDesc") %>' >
                        </asp:DropDownList>
                        <asp:ObjectDataSource ID="odsPunchTypes" runat="server" OldValuesParameterFormatString="original_{0}" SelectMethod="GetData" TypeName="SOSiQ.SOSiQsqlDBTableAdapters.ShowMeThePunchTypesTableAdapter"></asp:ObjectDataSource>
                    </EditItemTemplate>
                    <FooterTemplate>    
                        <asp:DropDownList ID="ddPunchTypeFooter" runat="server" DataSourceID="odsPunchTypes" DataTextField="PunchTypeDesc" DataValueField="PunchTypeID">
                        </asp:DropDownList>
                        <asp:ObjectDataSource ID="odsPunchTypes" runat="server" OldValuesParameterFormatString="original_{0}" SelectMethod="GetData" TypeName="SOSiQ.SOSiQsqlDBTableAdapters.ShowMeThePunchTypesTableAdapter"></asp:ObjectDataSource>
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lblPunchType" runat="server" Text='<%# Bind("PunchTypeDesc") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>

            <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#0000A9" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#000065" />
        </asp:GridView>

        <asp:ObjectDataSource ID="odsTimeStamps" runat="server" OldValuesParameterFormatString="original_{0}" SelectMethod="GetData" TypeName="SOSiQ.SOSiQsqlDBTableAdapters.ShowMeTheEmployeeTimeStampsTableAdapter">
            <SelectParameters>
               
                <asp:ControlParameter ControlID="ddlTeamMembers" Name="EmpID" PropertyName="SelectedValue" Type="Int32" />
               
              <asp:ControlParameter ControlID="txtDate" Name="_Date" PropertyName="Text" Type="DateTime" />
            </SelectParameters>
        </asp:ObjectDataSource>

    </div>

</asp:Content>
