'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditWorkOrder

    '''<summary>
    '''lblPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDateBegin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateBegin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDateEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateEnd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUpdateTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateTable As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddOrderStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddOrderStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''odsOrderStatusFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsOrderStatusFilter As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''btnResetTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetTable As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSelectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSelectAll As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUnselectAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUnselectAll As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnMarkReadyForInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMarkReadyForInvoice As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEditOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditOrder As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvOrdersToEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOrdersToEdit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsOrdersToEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsOrdersToEdit As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
